// packages/playground/src/components/CardList/index.tsx
import type { Component } from 'solid-js'
import { For, createSignal } from 'solid-js'
import { AsciiMath } from '../../../../core'
import { Card } from '../Card'
import './index.css'

const CardList: Component = () => {
  const [items, setItems] = createSignal([0])
  const am = new AsciiMath()
  return (
    <>
      <For each={items()}>
        {(_item, i) => (
          <div class="mb-4 w-full flex-no">
            <Card am={am} />
            <button
              style={{ 'font-family': 'KaTeX_Main' }}
              onClick={() => setItems(p => [...p.slice(0, i()), ...p.slice(i() + 1)])}
            >-
            </button>
          </div>
        )}
      </For>
      <button
        class="w-full mb-1rem"
        onClick={() => setItems(p => [...p, Date.now()])}
        style={{ 'font-family': 'KaTeX_Main' }}
      >+
      </button>
    </>
  )
}

export {
  CardList,
}

// example/src/lib/CardList.svelte
<script lang="ts">
  import Card from "./Card.svelte";
  import type { AsciiMath } from "../../../packages/core/src/index";
  export let am: AsciiMath;
  let items: number[] = [0];

  function addItem() {
    items[items.length] = Date.now();
  }

  function removeItem(i: number) {
    if (items.length === 1) return;
    items = [...items.slice(0, i), ...items.slice(i + 1)];
  }
</script>

<div>
  {#each items as item, i (item)}
    <div class="mb-4 w-full flex">
      <Card {am} />
      <button on:click={() => removeItem(i)} style="font-family: KaTeX_Main"
        >-</button
      >
    </div>
  {/each}
  <button
    class="w-full mb-1rem"
    on:click={addItem}
    style="font-family: KaTeX_Main">+</button
  >
</div>

<style>
  .flex {
    display: flex;
  }
  .w-full {
    width: 100%;
  }
  .mb-4 {
    margin-bottom: 1rem;
  }
</style>
