// packages/playground/src/components/SymbolTable/index.tsx
import type { Component } from 'solid-js'
import { For } from 'solid-js'
import type { AsciiMath } from '@am'
import { renderTex } from '~/utils/renerTex'

function arrayToMatrix<T>(arr: T[], cols: number) {
  const res = []
  for (let i = 0; i < arr.length; i += cols)
    res.push(arr.slice(i, i + cols))
  return res
}

const TableRow: Component<{
  am: AsciiMath
  symbols: string[]
}> = ({ am, symbols }) => {
  return (
    <tr>
      <For each={symbols}>
        {b => (
          <>
            <td class="tex tc" innerHTML={renderTex(am, b)}></td>
            <td class="tc">{b}</td>
          </>
        )}
      </For>
    </tr>
  )
}

const SymbolTable: Component<{
  am: AsciiMath
  symbols: string[]
  cols?: number
}> = ({ am, symbols, cols = 4 }) => {
  const symbolMatrix = arrayToMatrix(symbols, cols)
  return (
    <table>
      <For each={symbolMatrix}>
        {a => <TableRow am={am} symbols={a} />}
      </For>
    </table>
  )
}

export {
  SymbolTable,
}

// example/src/lib/SymbolTable.svelte
<script lang="ts">
  import type { AsciiMath } from "../../../src";
  import { renderTex } from "./renderTex";
  export let am: AsciiMath;
  export let symbols: string[];
  export let cols: number = 4;

  let symbolMatrix = (() => {
    let temp: string[] = [];
    let res: string[][] = [];
    for (let i = 0; i < symbols.length; i++) {
      temp.push(symbols[i]);
      if (temp.length === cols) {
        res.push(temp);
        temp = [];
      }
    }
    if (temp.length) res.push(temp);
    return res;
  })();
</script>

<table>
  <tbody>
    {#each symbolMatrix as symbolArray}
      <tr>
        {#each symbolArray as s}
          <td class="tex tc">{@html renderTex(am, s)}</td>
          <td class="tc">{s}</td>
        {/each}
      </tr>
    {/each}
  </tbody>
</table>
